title: Data Science With Python
logo: /assets/img/logo.png
description: Democratizing Data Science
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
docs_list_title: Documentation
docs:
- title: Introduction
  url: introduction.html
